# coding: utf-8
from pathlib import Path
import json,html
r=Path(__file__).parent;M=json.loads((r/'art-manifest.json').read_text())
for m in M:
 p=r/'art'/m['slug'];p.mkdir(exist_ok=True)
 page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>TITLE / Touching the Quiet</title><link rel="stylesheet" href="../../assets/art/viewer.css?v=3"></head><body style="--paper:BG;--ink:ACCENT"><canvas id="art" aria-label="Interactive TITLE canvas"></canvas><header><a class="back" href="../../" aria-label="Back to collection">←</a><div><span>LABEL</span><h1>TITLE</h1></div><div class="header-tools"><button id="reset" aria-label="Start over">↺</button><button id="guide" aria-label="Show interaction guide">?</button><button id="quiet" aria-label="Hide interface">⛶</button></div></header><div id="notice" aria-live="polite">HINT</div><footer><div id="tools" class="tools" aria-label="Scene-specific tools"></div></footer><button id="restore" aria-label="Show interface" hidden>＋</button><!-- Dynamics adapted from Mouse Twitch by maks. CC BY-NC-SA 3.0. Full attribution in ART-CREDITS.md. --><script>window.ART=META;</script><script src="../../assets/art/interactions.js?v=3"></script><script src="../../assets/art/engine.js?v=3"></script><script src="../../assets/art/viewer.js?v=3"></script></body></html>'''
 for a,b in [('TITLE',html.escape(m['name'])),('LABEL',m['english']),('BG',m['bg']),('ACCENT',m['accent']),('HINT',html.escape(m['hint'])),('META',json.dumps(m,ensure_ascii=False))]:page=page.replace(a,b)
 (p/'index.html').write_text(page)
 (p/'README.md').write_text(f'# {m["name"]}\n\n{m["description"]}\n\n## Interaction\n{m["hint"]}\n\nModel: {m["mechanic"]}. Scene-specific input, persistent state and simulation are in assets/art/interactions.js. Rendering and interpolation are shared; there is no generic touch-repulsion interaction.\n\nSpring interpolation derived from Mouse Twitch / maks: https://openprocessing.org/@maksss/3026808 . New shape, input and simulation authored for this collection. CC BY-NC-SA 3.0, https://creativecommons.org/licenses/by-nc-sa/3.0/ . Original source: originals/12-particle-twitch/mySketch.\n')
print('20 English scene pages generated; no source links in the art interface.')
