# coding: utf-8
from pathlib import Path
import json,html
r=Path(__file__).parent;M=json.loads((r/'art-manifest.json').read_text());cards=[]
for i,m in enumerate(M):
 cards.append(f'''<a class="card {'large' if i<2 else ''}" href="art/{m['slug']}/" data-kind="{m['kind']}" data-category="{m['category']}" aria-label="Enter {m['name']}" style="--paper:{m['bg']};--ink:{m['accent']}"><div class="picture"><canvas aria-label="{m['name']} preview"></canvas><span class="number">{i+1:02d} / 20</span><span class="enter">Enter study ↗</span></div><div class="caption"><h2>{m['name']}</h2><span class="cat">{m['category']}</span></div><p>{m['description']}</p></a>''')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Twenty interactive studies with twenty distinct ways to play. Feed, sculpt, fold, scratch, plant, weave, and discover."><title>Touching the Quiet / Twenty ways to play</title><link rel="stylesheet" href="assets/art/gallery.css?v=3"></head><body><header><a href="./" class="brand">Quiet / Play<small>INTERACTIVE STUDIES</small></a><nav><a href="#works">Explore</a><a class="download" href="downloads/touch-art-20.zip" download>Download collection ↓</a></nav></header><main><section class="intro"><div><div class="eyebrow">TWENTY STUDIES · TWENTY WAYS TO PLAY</div><h1>A different world.<br>A different <em>gesture.</em></h1></div><aside><p class="quote">Small worlds.<br>Unexpected responses.</p><p>Feed a fish. Fold a wing. Wipe a window.<br>Scratch a record. Plant a little garden.<br>Your hands leave more than a ripple.</p><div class="rule">SCULPT · FEED · WEAVE · FOLD · ORBIT</div></aside></section><section class="gallery" id="works"><div class="toolbar"><div class="filters" aria-label="Browse by subject">FILTERS</div><span id="count">20 STUDIES · FIND YOUR GESTURE</span></div><div class="grid">CARDS</div></section></main><footer><div>Quiet / Play · 2026<br>With attribution to maks · CC BY-NC-SA 3.0.</div><div>Made for hands, not scores.</div></footer><script src="assets/art/interactions.js?v=3"></script><script src="assets/art/engine.js?v=3"></script><script src="assets/art/gallery.js?v=3"></script></body></html>'''
filters=''.join(f'<button data-filter="{x}" class="{"active" if x=="All" else ""}">{x}</button>' for x in ['All','Portraits','Landscapes','Creatures','Botanical','Everyday','Light studies'])
(r/'index.html').write_text(page.replace('FILTERS',filters).replace('CARDS','\n'.join(cards)))
print('English gallery generated.')
