"""Package 20 independent interactive art scenes and an editorial download catalogue."""
from pathlib import Path
import json,zipfile,shutil
R=Path(__file__).parent;G=R/'art20'
for d in ['standalone','packages','previews']:(G/d).mkdir(exist_ok=True)
def button(text,action,value='',group='',active=False,cls=''):
    return f'<button class="{cls}" data-action="{action}" data-value="{value}"'+(f' data-group="{group}" aria-pressed="{str(active).lower()}"' if group else '')+f'>{text}</button>'
def swatch(col,action,value,group,active=False,label=''):
    return f'<button class="swatch" aria-label="{label or col}" style="--swatch:{col}" data-action="{action}" data-value="{value}" data-group="{group}" aria-pressed="{str(active).lower()}"></button>'
def ranger(action,label,minimum,maximum,value,step='.01'):
    return f'<label class="row"><small>{label}</small><input aria-label="{label}" data-action="{action}" type="range" min="{minimum}" max="{maximum}" step="{step}" value="{value}"></label>'
def head(tag,title,hint='',extra=''):
    return f'<div class="head {extra}"><small>{tag}</small><h1>{title}</h1>'+ (f'<p class="hint">{hint}</p>' if hint else '')+'</div>'
def bottom(content,cls=''):
    return f'<div class="bottom {cls}">{content}</div>'
b=button;s=swatch
items=[]
def add(slug,name,klass,bg,ink,accent,hint,gesture,ui):
    items.append(dict(slug=slug,name=name,klass=klass,bg=bg,ink=ink,accent=accent,hint=hint,gesture=gesture,ui=ui))
add('01-koi-sanctuary','Koi Sanctuary','koi','#294f4b','#f2ebd4','#e4be80','Tap to feed. Drag a lily pad. The koi follow the food.','Feed · move lilies · night pond',
 head('01 / A quiet ecosystem','Koi Sanctuary')+bottom('<div class="row"><div class="spacer"><h2>Let the water<br>find you.</h2><p class="hint" style="margin-top:10px">Tap to feed. Drag the floating leaves.</p></div><div class="vertical">'+b('＋ Feed','feed')+b('☾ Night','night')+b('New pond','reset')+'</div></div>'))
add('02-clay-hour','Clay Hour','pottery','#e5d9c7','#674e3e','#9c5e43','Drag either wall to shape wet clay. Fire the vessel to finish it.','Sculpt walls · choose glaze · fire',
 head('Wheel session / 02','Clay Hour','A small vessel, made by your hands.','center')+ '<div class="side key">RIM<br>│<br>│<br>│<br>│<br>FOOT</div>'+bottom('<div class="dock"><div class="vertical"><small>Glaze</small><div class="tools">'+s('#b87250','glaze','0','glaze',True,'Terracotta glaze')+s('#477e88','glaze','1','glaze',False,'Celadon glaze')+s('#b5a99d','glaze','2','glaze',False,'Chalk glaze')+'</div></div><div class="spacer"></div>'+b('Fire vessel','fire')+b('↺','reset',cls='icon')+'</div><div class="row" style="margin-top:12px"><p class="hint spacer">Drag the clay walls inward or outward.</p><span class="status" data-status>WET CLAY</span></div>'))
add('03-silk-memory','Silk Memory','loom','#31384b','#f2d9d0','#d48d86','Pull the cloth. Its woven threads hold, stretch and settle.','Pull cloth · release folds · wind',
 head('Woven matter / specimen 03','Silk Memory')+'<div class="side vertical">'+s('#d44848','weave','0','weave',True,'Persimmon weave')+s('#568a93','weave','1','weave',False,'Lagoon weave')+s('#c197bf','weave','2','weave',False,'Lilac weave')+b('≋','wind',cls='icon')+'</div>'+bottom('<div class="row hairline"><p class="hint spacer">Pull any part of the fabric.<br>Release and watch the weave remember.</p>'+b('Rehang','reset')+'</div>'))
add('04-balance-in-air','Balance in Air','mobile','#e1e8eb','#3f4c54','#a04f3e','Drag a hanging shape. Release it and watch the whole mobile rebalance.','Pull · swing · change shapes',
 head('A kinetic object / 04','Balance in Air')+bottom('<div style="margin-left:36px"><p class="hint">One touch moves everything.<br>Pull a shape and let go.</p><div class="tools" style="margin-top:14px">'+b('A little breeze','breeze')+b('Change forms','turn')+b('Rebalance','reset')+'</div></div>'))
add('05-tea-for-one','Tea for One','tea','#d2e6d9','#3b6557','#597d69','Move and tilt the teapot over the cup. Stir the surface with a finger.','Move teapot · pour · stir',
 head('The slow table — 05','Tea for One')+bottom('<div class="row" style="align-items:end"><div class="spacer"><small>Today’s infusion</small><div class="tools" style="margin:12px 0">'+b('Jasmine','tea','0','tea',True)+b('Hibiscus','tea','1','tea')+b('Oolong','tea','2','tea')+'</div><p class="hint">Move the pot over the cup. Touch the tea to stir.</p></div><div class="vertical">'+b('Pour / stop','pour')+b('Fresh cup','reset')+'</div></div><p data-status class="status" style="margin-top:14px">15% · Jasmine</p>'))
add('06-aurora-dunes','Aurora Dunes','aurora','#132838','#e6e9db','#b3d7b7','Sweep the sky to bend the curtains of light. Tap to place a star.','Bend light · place stars · wind',
 head('06 / Polar studies','Aurora<br>Dunes','Sweep the sky. Leave a star.')+bottom('<div class="row hairline"><div class="spacer">'+ranger('wind','Wind',-2,2,.5)+'</div>'+b('Pink dawn','sky')+b('New sky','reset')+'</div>'))
add('07-rain-room','Rain Room','window','#9fb7b7','#274d5c','#406c7a','Wipe the mist away to reveal the evening city. Raindrops slowly clear their own paths.','Wipe glass · reveal city · change rain',
 head('ROOM 07 / WINDOW STUDY','Rain Room')+bottom('<div class="row"><div class="spacer"><span class="badge">18° / EVENING RAIN</span><p class="hint" style="margin-top:12px">Draw on the mist.<br>There is a city on the other side.</p></div><div class="vertical">'+b('Drizzle / on','weather')+b('Mist the glass','fog')+'</div></div>'))
add('08-lantern-jellies','Lantern Jellies','jelly','#0d2036','#d2e1ed','#b6bbdf','Lead a jellyfish by its bell. Its long tentacles follow the current.','Guide bells · bend tentacles · pulse',
 head('ABYSS / FIELD NOTE 08','Lantern Jellies')+'<div class="side vertical"><div class="key">LIGHT<br>│<br>│<br>│<br>│<br>DEEP</div></div>'+bottom('<div class="row"><p class="hint spacer">Take a bell by the hand.<br>Move slowly. The tentacles follow.</p><div class="vertical">'+b('Send a current','current')+b('New life','life')+'</div></div>'))
add('09-sand-ritual','Sand Ritual','sand','#d7c9a9','#6a614e','#716a54','Rake parallel grooves. Switch tools to move stones, then draw rings around them.','Rake · arrange stones · concentric rings',
 head('09 / A garden without hurry','Sand Ritual')+bottom('<div class="tools hairline">'+b('≋ Rake','mode','rake','mode',True)+b('◒ Stones','mode','stones','mode')+b('◎ Rings','circles')+b('Smooth sand','reset')+'</div><p class="hint" style="margin-top:12px">Rake with a sweep. Arrange the stones by hand.</p>'))
add('10-glass-orchard','Glass Orchard','glass','#30323d','#e4d2b3','#cf9b70','Move the lead joints to reshape individual glass cells. Shift the sunlight.','Drag joints · refract light · recolour',
 head('A window in colour / 10','Glass Orchard','','center')+bottom('<div class="center"><p class="hint" style="margin:0 auto 15px">Move a joint. The whole window changes.</p><div class="tools">'+ranger('light','Sunlight',0,1,.5)+b('Change glass','palette')+b('New window','reset')+'</div></div>'))
add('11-pocket-meadow','Pocket Meadow','meadow','#e9ead1','#526b50','#6e8557','Plant a flower with a touch. Comb the meadow with the breeze or scatter drifting seeds.','Plant · comb stems · scatter seeds',
 head('A living herbarium / 11','Pocket<br>Meadow')+bottom('<div class="row"><div class="tools spacer">'+b('Plant','mode','seed','mode',True)+b('Breeze','mode','comb','mode')+'</div><div class="seal">GROWN<br>BY YOU</div></div><div class="row" style="margin-top:13px"><p class="hint spacer">Touch to plant. Sweep to bend.</p>'+b('Scatter seeds','seedfall')+b('↺','reset',cls='icon')+'</div>'))
add('12-paper-aviary','Paper Aviary','fold','#d3e1ed','#3c5e79','#6e8b9d','Touch to fold a paper bird. Pick one up and flick it into flight.','Fold · pick up · launch birds',
 head('FOLD / RELEASE / REPEAT','Paper Aviary')+bottom('<div class="row hairline"><div class="spacer"><small>01 Fold &nbsp; 02 Pick up &nbsp; 03 Flick</small><div class="tools" style="margin-top:13px">'+s('#e8c76d','paper','0','paper',True,'Ochre paper')+s('#bc8795','paper','1','paper',False,'Rose paper')+s('#89a9b7','paper','2','paper',False,'Blue paper')+'</div></div><div class="vertical">'+b('Fold a bird','fold')+b('Open the sky','release')+'</div></div>'))
add('13-tectonic-atlas','Tectonic Atlas','atlas','#d8e3e6','#4c6268','#77865b','Touch the land to raise hills, carve valleys or smooth the terrain. Turn the map.','Raise terrain · carve · smooth · rotate',
 head('13 / LANDSCAPE IN THE MAKING','TECTONIC<br>ATLAS')+'<div class="side vertical">'+b('＋','mode','raise','mode',True,'icon')+b('−','mode','carve','mode',False,'icon')+b('≈','mode','smooth','mode',False,'icon')+'</div>'+bottom('<div class="row hairline"><div class="spacer">'+ranger('turn','Turn',-.8,1.3,.4)+'</div>'+b('Contours on','contour')+b('New land','reset')+'</div><p class="hint" style="margin-top:12px">＋ Raise &nbsp; − Carve &nbsp; ≈ Smooth<br>Press the land with your finger.</p>'))
add('14-orbital-forge','Orbital Forge','orbit','#1b2430','#e8d9bc','#dba266','Drag backward and release to launch a planet. Let gravity draw its orbit.','Slingshot · orbit · vary mass',
 head('14 / GRAVITY EXPERIMENT','ORBITAL<br>FORGE')+'<div class="side key" data-status>05 BODIES</div>'+bottom('<div class="row hairline"><p class="hint spacer">Pull back. Release a planet.<br>Gravity draws the rest.</p><div class="vertical">'+b('Mass · light','mass')+b('Clear orbits','clear')+b('Restore system','reset')+'</div></div>'))
add('15-bubble-conservatory','Bubble Conservatory','bubbles','#d9cee4','#665b7a','#938eab','Hold empty space to blow a bubble. Drag to carry it. Tap an existing bubble to pop it.','Blow · carry · pop · slow time',
 head('15 / ephemeral objects','bubble<br>conservatory')+bottom('<div class="row"><p class="hint spacer">Hold to blow.<br>Carry gently. Tap to let go.</p><div class="vertical pill">'+b('Breathe out','breath')+b('Slow motion','slow')+'</div></div>'))
add('16-coral-architect','Coral Architect','coral','#dcd5e7','#605872','#9c6a79','Graft a new branch. Hold near growing tips to guide them. Switch to pruning to open space.','Graft · guide growth · prune',
 head('16 / An underwater nursery','Coral<br>Architect')+'<div class="side vertical">'+s('#bd6b72','pigment','0','pigment',True,'Coral pigment')+s('#798cb6','pigment','1','pigment',False,'Lavender pigment')+s('#97a579','pigment','2','pigment',False,'Sage pigment')+'</div>'+bottom('<div class="row"><div class="tools spacer">'+b('Graft','mode','graft','mode',True)+b('Prune','mode','prune','mode')+b('Start a reef','reset')+'</div></div><p class="hint" style="margin-top:14px">Touch to graft. Hold near a tip to guide it.<br>Make a little room for new life.</p>'))
add('17-constellation-harp','Constellation Harp','harp','#1d2033','#e3d6bc','#c8b08b','Brush a string to set it vibrating. Move the stars to tune its geometry. Sound is optional.','Pluck strings · move stars · optional tones',
 head('A nocturne for your hands / 17','Constellation<br>Harp')+bottom('<div class="row hairline"><div class="spacer"><div class="tools">'+b('Pluck','mode','pluck','mode',True)+b('Move stars','mode','tune','mode')+'</div><p class="hint" style="margin-top:12px">Brush a string. Listen only if you wish.</p></div><div class="vertical">'+b('Sound off','sound')+b('Play a chord','chord')+'</div></div>'))
add('18-petal-lens','Petal Lens','lens','#4d303d','#ecd9c2','#d1a27b','Paint inside the lens. Turn its material into petals, sea glass or moth wings.','Stamp · mirror · rotate · change material',
 head('18 / PATTERN CAMERA','Petal Lens')+ '<div class="viewfinder"></div>'+bottom('<div class="center"><p class="status" data-status>DAHLIA / PETALS</p><div class="tools" style="justify-content:center;margin:12px 0">'+b('6','folds','6','folds')+b('8','folds','8','folds',True)+b('12','folds','12','folds')+b('Paint','mode','paint','mode',True)+b('Turn','mode','turn','mode')+'</div><div class="tools" style="justify-content:center">'+b('Change material','material')+b('Fresh lens','reset')+'</div></div>'))
add('19-tide-table','Tide Table','tide','#e4dbc5','#3f6e70','#618f8c','Move shells by hand. Leave marks in the sand and raise the tide to wash them away.','Arrange shells · trace sand · raise tide',
 head('POSTCARD No. 19','Tide Table','A shore that never stays the same.')+bottom('<div class="row hairline"><div class="spacer">'+ranger('tide','Tide',0,1,.5)+'</div>'+b('Another shell','shells')+'</div><p class="hint" style="margin-top:12px">Move a shell. Draw on the sand.<br>The water will take its time.</p>'))
add('20-portrait-of-air','Portrait of Air','mask','#4a3647','#efdccc','#c59d85','Drag the mouth, brow or cheek to reshape an expression. The eyes follow your hand.','Shape expression · stretch face · change finish',
 head('20 / AN EXPRESSION STUDY','Portrait<br>of Air')+bottom('<div class="row"><div class="tools spacer">'+b('Calm','expression','0','expression',True)+b('Smile','expression','1','expression')+b('Curious','expression','2','expression')+'</div>'+b('New finish','material')+'</div><p class="hint" style="margin-top:14px">Touch the little guides.<br>Move the mouth, brow or cheek.</p>'))

runtime=(G/'runtime.js').read_text();css=(G/'interface.css').read_text()
for e in items:
    source=(G/'src'/f"{e['slug']}.js").read_text()
    if e['slug'].startswith('10-'):source=(R/'research/more-art/916227-frozen/delaunay.js').read_text()+'\n'+source
    e['license']='CC BY-SA 3.0' if e['slug'].startswith('10-') else 'MIT'
    d=G/e['slug'];d.mkdir(exist_ok=True)
    (d/'scene.js').write_text(source)
    colors=f":root{{--bg:{e['bg']};--ink:{e['ink']};--accent:{e['accent']};--glass:color-mix(in srgb,var(--bg) 72%,transparent);--line:color-mix(in srgb,var(--ink) 22%,transparent)}}"
    shell='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>'+e['name']+'</title>'
    body=f'''<body class="{e['klass']}"><canvas aria-label="{e['name']} interactive artwork"></canvas><main class="ui">{e['ui']}<div class="corner">{b('◌','quiet',cls='icon')}</div></main><button class="reveal" data-reveal aria-label="Show interface">◌</button><div id="error" role="alert"></div>'''
    # Give symbol buttons meaningful accessible names.
    body=body.replace('data-action="quiet"','aria-label="Hide interface" data-action="quiet"')
    body=body.replace('>↺</button>', ' aria-label="Reset artwork">↺</button>').replace('>≋</button>', ' aria-label="Send a breeze">≋</button>')
    if e['klass']=='atlas':
        for symbol,label in [('＋','Raise terrain'),('−','Carve terrain'),('≈','Smooth terrain')]:
            body=body.replace('>'+symbol+'</button>',' aria-label="'+label+'">'+symbol+'</button>')
    ext=shell+'<link rel="stylesheet" href="../interface.css"><style>'+colors+'</style></head>'+body+'<script src="scene.js"></script><script src="../runtime.js"></script></body></html>'
    (d/'index.html').write_text(ext)
    license='Interactive artwork: '+e['name']+'\n'+('Adapted Delaunay triangulation from Frozen Brush 2 by Jason Labbe, https://openprocessing.org/@theRussetPotato/916227\nOriginal library attribution to Jay LaPorte is preserved in the source. Original and adaptation CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/\nChanges: stained glass geometry, joint editing, light, touch, offline Canvas implementation.\n' if e['slug'].startswith('10-') else 'Original Canvas implementation created for this collection.\nMIT License\nCopyright (c) 2026 Tao\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n')
    (d/'LICENSE.txt').write_text(license)
    def safe(t):return t.replace('</script','<\\/script')
    html=shell+'<!-- '+license.replace('--','—')+' --><style>'+css+colors+'</style></head>'+body+'<script>'+safe(source)+'</script><script>'+safe(runtime)+'</script></body></html>'
    (G/'standalone'/f"{e['slug']}.html").write_text(html)
    with zipfile.ZipFile(G/'packages'/f"{e['slug']}.zip",'w',zipfile.ZIP_DEFLATED) as z:
        z.writestr('index.html',html);z.writestr('LICENSE.txt',license);z.writestr('source/scene.js',source);z.writestr('source/runtime.js',runtime);z.writestr('source/interface.css',css)
        z.writestr('UPLOAD.txt','Upload this ZIP with index.html at its root, or use the separate standalone HTML. No external fonts, libraries, images, network calls or integrations are required.\n'+e['hint'])
        if e['slug'].startswith('10-'):z.write(R/'research/more-art/916227-frozen/delaunay.js','original/delaunay.js')

manifest=[{k:v for k,v in e.items() if k!='ui'} for e in items]
(G/'manifest.json').write_text(json.dumps(manifest,indent=2))
cards=''.join(f'''<article data-category="{e['gesture']}"><a class="preview" href="{e['slug']}/"><img src="previews/{e['slug']}.jpg" alt="{e['name']} actual artwork preview"></a><div class="caption"><span>{e['slug'][:2]} / {e['gesture'].split(' · ')[0].upper()}</span><h2>{e['name']}</h2><p>{e['hint']}</p><nav><a href="{e['slug']}/">Enter ↗</a><a href="standalone/{e['slug']}.html" download>HTML ↓</a><a href="packages/{e['slug']}.zip" download>ZIP ↓</a></nav></div></article>''' for e in items)
gallery_css='''*{box-sizing:border-box}body{margin:0;background:#eeece6;color:#323c3b;font-family:Arial,sans-serif}header{max-width:1400px;margin:auto;padding:50px 34px 35px;display:flex;gap:40px;align-items:end;justify-content:space-between}.kicker{font-size:10px;letter-spacing:3px}h1{font:clamp(45px,7vw,94px) Georgia,serif;line-height:1;margin:18px 0 0;letter-spacing:-3px}.intro{max-width:335px;font-size:13px;line-height:1.8;color:#7a7e76}.count{font:56px Georgia;display:block;color:#7f8c7c;margin-bottom:15px}.bar{max-width:1332px;margin:0 auto 28px;padding:16px 0;border-block:1px solid #b5b8ac66;display:flex;gap:20px;font-size:10px;letter-spacing:1.5px;color:#7b8174}.grid{max-width:1400px;margin:auto;padding:0 34px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}article{background:#f8f6f0;overflow:hidden;border:1px solid #c2c3b522;border-radius:4px}.preview{display:block;height:325px;background:#d9d8ce;overflow:hidden}.preview img{width:100%;height:100%;object-fit:cover;object-position:center 43%}.caption{padding:21px}.caption span{font-size:9px;letter-spacing:1.6px;color:#8b8d7e}h2{font:24px Georgia;margin:10px 0 13px}.caption p{font-size:11px;line-height:1.8;color:#7a7d72;min-height:58px}nav{display:flex;gap:13px;flex-wrap:wrap}a{color:inherit;text-decoration:none}nav a{font-size:10px;border-bottom:1px solid #a4ad9b;padding:5px 0}nav a:first-child{color:#506b55}footer{max-width:1400px;margin:auto;padding:45px 34px;font-size:11px;line-height:1.8;color:#888b80}footer a{text-decoration:underline}button{font:11px Arial;border:1px solid #bac0b0;background:#e0e6d9;color:#4e624d;padding:11px 16px;cursor:pointer;border-radius:2px}.links{display:flex;gap:10px;margin-top:20px}.links a{padding:11px 16px;background:#dce4d5;font-size:11px}.list{margin:25px 34px;max-width:1332px;font-size:11px;line-height:2}details{max-width:1332px;margin:25px auto;padding:18px;border:1px solid #c2c3b588}summary{cursor:pointer;font-size:12px}.downloads{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding-top:20px}.downloads a{font-size:11px;color:#536d52}@media(max-width:1100px){.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:820px){.grid{grid-template-columns:repeat(2,1fr)}header{display:block}.intro{margin-top:25px}.count{display:none}.bar{margin-inline:25px}.downloads{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){header{padding:32px 20px}.grid{padding:0 18px;gap:18px;grid-template-columns:1fr}.preview{height:440px}.caption p{min-height:0}h1{letter-spacing:-2px}.bar{font-size:8px;gap:12px}details{margin:20px 18px}.downloads{grid-template-columns:1fr}}'''
links=''.join(f'<a href="packages/{e["slug"]}.zip" download>{e["slug"][:2]} · {e["name"]} / ZIP ↓</a>' for e in items)
(G/'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Twenty Ways to Touch</title><style>'+gallery_css+'</style></head><body><header><div><span class="kicker">COLLECTION THREE / INTERACTIVE ART</span><h1>Twenty ways<br>to touch.</h1></div><div class="intro"><span class="count">20</span>Living things, quiet objects and small worlds.<br>Twenty independent artworks. Different gestures, different materials, different interfaces.<div class="links"><a href="twenty-touch-artworks.zip" download>Download all ZIPs ↓</a><a href="#downloads">Individual files ↘</a></div></div></header><div class="bar"><span>TOUCH & MOUSE</span><span>ENGLISH</span><span>OFFLINE HTML</span><span>ONE ZIP PER ARTWORK</span></div><main class="grid">'+cards+'</main><details id="downloads"><summary>20 individual ZIP downloads</summary><div class="downloads">'+links+'</div></details><footer>Every artwork is independent. Download a single HTML or its ZIP with index.html at the root.<br><a href="../upload-art/">Collection one</a> &nbsp; / &nbsp; <a href="../upload-art-2/">Collection two</a></footer></body></html>')
with zipfile.ZipFile(G/'twenty-touch-artworks.zip','w',zipfile.ZIP_DEFLATED) as z:
    for e in items:z.write(G/'packages'/f"{e['slug']}.zip",f"{e['slug']}.zip")
    z.writestr('READ-ME.txt','20 separate upload packages. Choose one ZIP for each upload. Every individual ZIP contains index.html at its root. Standalone HTML files are also available on the preview page.\n')
(G/'release-notes.txt').write_text('Twenty Ways to Touch\n\n20 independent interactive artworks with distinct content, gestures and interfaces.\n\nEach artwork has an offline single HTML and an individual ZIP with index.html at the root. No external runtime assets or platform integration are required. English interfaces. The complete download contains all 20 individual ZIPs.\n\n'+ '\n'.join(e['name']+' — '+e['gesture'] for e in items))
print('Built 20 offline HTML files, 20 individual upload ZIPs, and one complete download.')
