
// Splash! by Jason Labbe: target-seeking droplets split once fast, then fall under gravity.
// Reskin: filled liquid typography, pigment, touch impulses, returning drops, no font file.
let drops=[],honeyWord=0,honeyPalette='honey',honeyTime=0,wordTargets=[];
const HONEY={honey:{bg:'#fff5df',dark:'#af691b',bright:'#f7cc59',shadow:'#c5893d'},berry:{bg:'#f9edf0',dark:'#8b385d',bright:'#ed96ab',shadow:'#bb6486'},mint:{bg:'#eaf3e9',dark:'#3f7866',bright:'#9dc7a5',shadow:'#5b927d'}};
function liquidDrop(x,y,tx,ty){return{pos:createVector(x,y),vel:createVector(0,0),acc:createVector(0,0),target:createVector(tx,ty),activate:false,recovering:false,fallVariance:random(.75,1.25),size:random(1.8,3.3),age:0,child:false,shine:random()>.78}}
function resetHoney(){const g=createGraphics(width,height);g.pixelDensity(1);g.textFont('Georgia');g.textStyle(BOLD);g.textAlign(CENTER,CENTER);g.textSize(min(width*.21,145));g.fill(255);g.text(['HONEY','LOVE','MELT'][honeyWord],width*.5,height*.43);g.loadPixels();wordTargets=[];const spacing=width<500?3.4:5;for(let y=height*.26;y<height*.59;y+=spacing)for(let x=width*.04;x<width*.96;x+=spacing){let i=(floor(y)*width+floor(x))*4;if(g.pixels[i+3]>100)wordTargets.push({x,y})}g.remove();drops=wordTargets.map(p=>liquidDrop(p.x,p.y,p.x,p.y));honeyTime=0}
function setup(){artCanvas();resetHoney();Studio.onDown=p=>splashNear(p,1.5);Studio.onMove=p=>splashNear(p,3+min(7,hypot(p.dx,p.dy)*.12));Studio.onTool=n=>{if(n==='word'){honeyWord=(honeyWord+1)%3;resetHoney()}else if(n==='pour'){for(const p of drops)if(!p.child){p.vel.add(random(-3,3),random(3,6))}}else{honeyPalette=n;Studio.select('palette',n);document.body.style.background=HONEY[n].bg}};Studio.onReset=resetHoney}
function splashNear(p,strength){for(const d of drops){const dx=d.pos.x-p.x,dy=d.pos.y-p.y,dd=hypot(dx,dy);if(dd<70&&dd>.01){d.recovering=false;d.vel.add(dx/dd*strength,dy/dd*strength-.3)}}}
function stepDrop(p){p.age++;if(!p.activate){if(p.vel.mag()>2.4&&!p.recovering){p.activate=true;p.age=0;if(!p.child&&drops.length<2300)for(let i=0;i<2;i++){let q=liquidDrop(p.pos.x,p.pos.y,p.target.x,p.target.y);q.activate=true;q.child=true;q.vel=p.vel.copy().rotate(random(-.35,.35)).mult(random(.7,1.2));q.size=random(1,2.5);drops.push(q)}}else{let d=p5.Vector.sub(p.target,p.pos),length=d.mag();if(length<3){p.recovering=false;p.vel.mult(.15)}p.vel.mult(.93);if(length>.2){d.normalize().mult(min(.36,length*.018));p.acc.add(d)}}}else{p.acc.y+=.17*p.fallVariance;p.vel.mult(.994);if(p.pos.y>height*.74){p.pos.y=height*.74;p.vel.y*=-.35;p.vel.x*=.95}if(p.age>90&&!p.child){p.activate=false;p.recovering=true;p.vel.mult(.08)}}
 for(const h of Studio.hands.values()){let d=p5.Vector.sub(p.pos,createVector(h.x,h.y)),l=d.mag();if(l>0&&l<55){d.normalize().mult((1-l/55)*.4);p.acc.add(d)}}p.vel.add(p.acc);p.vel.limit(12);p.pos.add(p.vel);p.acc.mult(0);if(p.pos.x<0||p.pos.x>width){p.pos.x=constrain(p.pos.x,0,width);p.vel.x*=-.5}}
function draw(){if(Studio.paused||Studio.suspended)return;honeyTime++;const s=HONEY[honeyPalette];background(s.bg);noStroke();fill(s.shadow+'16');ellipse(width*.5,height*.745,width*.82,15);
 for(let i=drops.length-1;i>=0;i--){const p=drops[i];stepDrop(p);if(p.child&&p.age>180){drops.splice(i,1);continue}const r=p.size*(p.activate?1.1:1);stroke(s.dark);strokeWeight(r*2);point(p.pos.x,p.pos.y);noStroke();fill(s.bright);circle(p.pos.x-r*.23,p.pos.y-r*.25,r*1.45);if(p.shine){fill('#fffce1');circle(p.pos.x-r*.25,p.pos.y-r*.4,r*.38)}}
}
function hypot(x,y){return Math.hypot(x,y)}
