
// Mutable ripples by Jason Labbe, Processing.js -> offline p5/Canvas projection.
// Original cube-shell sampling and distance-offset sine wave retained.
let pearlTime=0,rotX=-.3,rotY=.58,targetX=-.3,targetY=.58,pearlPalette='ivory',pulse=0,pulsePos={x:75,y:75,z:75},cube=[];
const PEARLS={ivory:{bg:'#222f36',hi:'#fffbe6',lo:'#8298a1'},jade:{bg:'#143b35',hi:'#edffe2',lo:'#41a998'},violet:{bg:'#29243e',hi:'#ffe9e7',lo:'#a191d1'}};
function setup(){artCanvas();for(let x=0;x<=144;x+=12)for(let y=0;y<=144;y+=12)for(let z=0;z<=144;z+=12)if(x===0||x===144||y===0||y===144||z===0||z===144)cube.push({x,y,z});Studio.onDown=p=>{pulse=1;pulsePos={x:p.x/width*144,y:p.y/height*144,z:72}};Studio.onMove=p=>{targetY+=p.dx*.009;targetX+=p.dy*.009;pulse=min(1,pulse+.06)};Studio.onTool=n=>{if(n==='wave'){pulse=1;pulsePos={x:random(144),y:random(144),z:random(144)}}else{pearlPalette=n;Studio.select('palette',n)}};Studio.onReset=()=>{rotX=targetX=-.3;rotY=targetY=.58;pulse=0;pearlTime=0}}
function projectPearl(x,y,z){let yy=y*cos(rotX)-z*sin(rotX),zz=y*sin(rotX)+z*cos(rotX),xx=x*cos(rotY)+zz*sin(rotY);zz=-x*sin(rotY)+zz*cos(rotY);const sc=min(width*.70,height*.5)/235*(400/(400-zz));return{x:width*.5+xx*sc,y:height*.46+yy*sc,z:zz,sc}}
function draw(){if(Studio.paused||Studio.suspended)return;pearlTime++;rotX=lerp(rotX,targetX,.08);rotY=lerp(rotY,targetY,.08);if(!Studio.hands.size){targetY+=.0018;pulse*=.985}else pulse=min(1,pulse+.015);const skin=PEARLS[pearlPalette];background(skin.bg);const ctx=drawingContext;let back=ctx.createRadialGradient(width*.5,height*.4,0,width*.5,height*.45,height*.65);back.addColorStop(0,skin.lo+'50');back.addColorStop(1,skin.bg);ctx.fillStyle=back;ctx.fillRect(0,0,width,height);noStroke();fill(0,35);ellipse(width*.5,height*.73,min(width*.6,350),18);
 let nx=noise(pearlTime*.007)*144,ny=noise(1000+pearlTime*.007)*144,nz=noise(5000+pearlTime*.007)*144;const data=cube.map(p=>{const d=Math.hypot(p.x-nx,p.y-ny,p.z-nz);let wave=sin((pearlTime+d)*.07);if(pulse>.01)wave+=sin(dist(p.x,p.y,pulsePos.x,pulsePos.y)*.095-pearlTime*.14)*pulse*.7;const q=projectPearl(p.x-72,p.y-72,p.z-72);return {...q,r:(3.5+3.5*(wave+1)/2)*q.sc,wave}}).sort((a,b)=>a.z-b.z);
 for(const p of data){const r=max(.7,p.r),g=ctx.createRadialGradient(p.x-r*.28,p.y-r*.32,.1,p.x,p.y,r);g.addColorStop(0,skin.hi);g.addColorStop(.36,skin.hi);g.addColorStop(.85,skin.lo);g.addColorStop(1,skin.bg);ctx.globalAlpha=.7+(p.z+130)/520;ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,TWO_PI);ctx.fill()}ctx.globalAlpha=1;
}
