from pathlib import Path
import json,re,hashlib,difflib,zipfile,html,shutil
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'remix20'; SRC=ROOT/'research/op-new-20'
works=[]
def add(id,slug,title,original,author,algo,changes,theme,layout,buttons,ranges,patches=(),hook='',init='',down='',move='',up='',actions='',extra=''):
 d=SRC/str(id)
 files=sorted([p for p in d.iterdir() if p.suffix=='.js' or p.name=='mySketch'])
 # Each source tab is preserved unchanged in original/. These patches alter that source directly.
 originalcode='\n\n'.join('// Original tab: '+p.name+'\n'+p.read_text() for p in files)
 code=originalcode
 for a,b in patches:
  if a not in code: raise Exception(f'{id} patch missing {a[:80]}')
  code=code.replace(a,b)
 meta=json.loads((SRC/(str(id)+'-metadata.json')).read_text()) if (SRC/(str(id)+'-metadata.json')).exists() else {}
 license=meta.get('license','unverified')
 work=dict(id=id,slug=slug,title=title,original=original,author=author,algorithm=algo,changes=changes,license=license,theme=theme,layout=layout,buttons=buttons,ranges=ranges,extra=extra)
 work['sourceFiles']=[{'name':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'url':f'https://preview.openprocessing.org/sketch/{id}/preview/false/{p.name}'} for p in files]
 (d/'source-tabs.json').write_text(json.dumps(work['sourceFiles'],indent=2))
 (d/'source-hashes.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in files},indent=2))
 adapter=f'''\n// Touch and UI adaptation; original visual algorithm above.\nR.init=()=>{{{init}}};\nR.frame=()=>{{{hook}}};\nR.down=()=>{{{down}}};\nR.move=()=>{{{move}}};\nR.up=()=>{{{up}}};\nR.action=(a,v)=>{{{actions}}};\n'''
 code=PREFIX+'\n'+code+'\n'+adapter+'\n'+WRAPPER
 folder=OUT/slug;folder.mkdir(exist_ok=True)
 (folder/'sketch.js').write_text(code)
 (folder/'adaptation.diff').write_text(''.join(difflib.unified_diff(originalcode.splitlines(True),(code[len(PREFIX)+1:code.index('// Touch and UI adaptation')]).splitlines(True),fromfile='OpenProcessing original tabs',tofile='Adapted visual code')))
 (folder/'source.json').write_text(json.dumps(work,indent=2,ensure_ascii=False))
 works.append(work)
PREFIX='''var R={x:0,y:0,px:0,py:0,pressed:false,touched:false,held:0,mode:0,palette:0,rate:1,amount:1,sign:1,paused:false,ink:0,init:()=>{},frame:()=>{},down:()=>{},move:()=>{},up:()=>{},action:()=>{}};'''
WRAPPER='''
const originalSetup=setup,originalDraw=draw;
setup=function(){pixelDensity(1);const cc=window.createCanvas;window.createCanvas=(w,h,...args)=>cc(windowWidth,windowHeight,...args);originalSetup();window.createCanvas=cc;R.x=width*.5;R.y=height*.48;R.px=R.x;R.py=R.y;R.init();
 const c=document.querySelector('canvas');c.setAttribute('aria-label','Interactive artwork');c.style.touchAction='none';
 document.querySelectorAll('body > input,body > button').forEach(e=>e.hidden=true);
 const sync=e=>{const b=c.getBoundingClientRect();R.x=(e.clientX-b.left)*width/b.width;R.y=(e.clientY-b.top)*height/b.height;mouseX=R.x;mouseY=R.y;pmouseX=R.px;pmouseY=R.py;};
 c.addEventListener('pointerdown',e=>{e.preventDefault();if(R.pointer!=null)return;R.pointer=e.pointerId;c.setPointerCapture?.(e.pointerId);sync(e);R.pressed=true;R.touched=true;R.held=0;R.px=R.x;R.py=R.y;mouseIsPressed=true;R.down();});
 c.addEventListener('pointermove',e=>{if(R.pointer!=null&&e.pointerId!==R.pointer)return;sync(e);R.touched=true;if(R.pressed)R.move();});
 const end=e=>{if(R.pointer!=null&&e.pointerId!==R.pointer)return;R.pressed=false;R.pointer=null;mouseIsPressed=false;R.up();};
 c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('lostpointercapture',end);
 document.addEventListener('visibilitychange',()=>{if(document.hidden){R.pressed=false;R.pointer=null;mouseIsPressed=false;R.up();}});
 document.querySelectorAll('button[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='quiet'){document.body.classList.toggle('quiet');b.textContent=document.body.classList.contains('quiet')?'Show UI':'Hide UI';return;}if(a==='pause'){R.paused=!R.paused;b.textContent=R.paused?'Resume':'Pause';return;}R.action(a);if(b.dataset.toggle!==undefined){b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')!=='true');}});
 document.querySelectorAll('input[data-action]').forEach(i=>{i.addEventListener('input',()=>{R.action(i.dataset.action,i.value);const o=i.parentNode.querySelector('output');if(o)o.textContent=i.value;});});
};
draw=function(){if(R.paused)return;if(!R.touched){R.x=width*(.5+.22*Math.sin(frameCount*.013));R.y=height*(.48+.13*Math.cos(frameCount*.019));}mouseX=R.x;mouseY=R.y;pmouseX=R.px;pmouseY=R.py;mouseIsPressed=R.pressed;if(R.pressed)R.held++;R.frame();originalDraw();R.px=R.x;R.py=R.y;};
// Pointer Events own input; prevent p5 synthesised clicks from resetting the artwork.
mousePressed=()=>false;mouseReleased=()=>false;mouseClicked=()=>false;mouseMoved=()=>false;mouseDragged=()=>false;touchStarted=()=>false;touchMoved=()=>false;touchEnded=()=>false;keyPressed=()=>false;
windowResized=function(){const ox=width,oy=height;resizeCanvas(windowWidth,windowHeight);R.x=R.x/ox*width;R.y=R.y/oy*height;R.px=R.x;R.py=R.y;R.resize?.(ox,oy);};
'''
add(434004,'01-velvet-grid','Velvet Grid','Warped','Jason Labbe','Distance-driven vector distortion of a point grid','Press to inflate; switch repulsion to attraction; spacing and porcelain/night palettes.','#131018|#f3bf87|#fbedd6','rail',[('reverse','Push / Pull'),('palette','Porcelain'),('relax','Release')],[('spacing','Grid',12,44,24,2)],
 [('var mouseSize = 300;','var mouseSize = 220; var gridGap=24;'),('background(0);','background(R.palette%2 ? "#fbedd6" : "#131018");'),('stroke(255);','stroke(R.palette%2 ? "#493459" : "#f3bf87");'),('y += 40','y += gridGap'),('x += 40','x += gridGap'),('pos.mult(0.25);','pos.mult(0.25*R.sign);')],
 hook='mouseSize=lerp(mouseSize,R.pressed?min(360,130+R.held*2):170,.06);',actions='if(a==="reverse")R.sign*=-1;if(a==="palette")R.palette++;if(a==="spacing")gridGap=+v;if(a==="relax"){R.touched=false;R.pressed=false;}')
add(684400,'02-prism-anemone','Prism Anemone','Organic','Jason Labbe','Radial noise-modulated spline fronds','Drag to bend; hold to bloom; adjustable frond density and opal/ember ink.','#130b28|#b1d5fd|#d4a8ff','editorial',[('palette','Opal / Ember'),('still','Still / Flow')],[('density','Fronds',.025,.09,.04,.005)],
 [('let f = frameCount;','let f = frameCount*R.rate;'),('background(0);','background(R.palette%2?"#27100a":"#130b28");'),('stroke(255);','stroke(R.palette%2?"#ffc780":"#b1d5fd");'),('translate(width / 2, height / 2);','translate(width/2+(mouseX-width/2)*.1,height*.48+(mouseY-height/2)*.1); scale(min(width,height)/1100*(R.pressed?1.15:1));'),('rad += 0.04','rad += R.amount'),('rotate(rad);','rotate(rad);strokeWeight(.7+1.5*sin(rad/2));')],init='R.amount=.04;',actions='if(a==="palette")R.palette++;if(a==="density")R.amount=+v;if(a==="still")R.rate=R.rate?0:1;')
add(423827,'03-lunar-lenses','Lunar Lenses','Circles nebula','Jason Labbe; intersection method credited in source','Circle-circle intersections rendered as translucent curved lenses','Drag a lens; hold to enlarge it; smooth/faceted modes, inversion, colour dial.','#071219|#82ded0|#e9fff5','float',[('facets','Soft / Facets'),('invert','Light / Dark'),('seed','New cluster')],[('hue','Spectrum',0,255,142,1)],
 [('var count = 50;','var count = 24;'),('allCircles[0].pos.set(mouseX, mouseY);','allCircles[0].pos.set(mouseX, mouseY); if(R.pressed)allCircles[0].diam=lerp(allCircles[0].diam,min(width*.8,100+R.held*2),.1);')],
 init='maxDiam=min(width*.92,450);reset();[hueSlider,hueRangeSlider,speedSlider].forEach(s=>s.display=()=>{});hueSlider.slider.value(142);',actions='if(a==="facets")toggleSmooth();if(a==="invert")toggleInvert();if(a==="seed")reset();if(a==="hue")hueSlider.slider.value(+v);')
add(447730,'04-chromatic-orrery','Chromatic Orrery','Motion study','Jason Labbe','Counter-rotating rings with sine-gated phase advances','Scrub rotation by dragging; choose square/disc marks; reverse orbit and adjust tempo.','#07090d|#f3ec8c|#f66bb6','split',[('reverse','Reverse orbit'),('marks','Squares / Discs')],[('tempo','Tempo',.15,3,1,.05)],
 [('var jCount = 40;','var jCount = 28;'),('a += 4','a += 6'),('translate(width/2, height/2);','translate(width/2,height*.48);rotate(R.ink);'),('jCount, 400, 5','jCount, min(width,height)*.43, 5'),('rect(0, 0, s, s);','if(R.mode%2)circle(0,0,s);else rect(0,0,s,s);'),('p.x += max(0, sin(p.j+frameCount*0.05)*shift);','p.x += max(0,sin(p.j+frameCount*.05*R.rate)*shift)*R.sign;')],move='R.ink+=(R.x-R.px)*.008;',actions='if(a==="reverse")R.sign*=-1;if(a==="marks")R.mode++;if(a==="tempo")R.rate=+v;')
add(605835,'05-dust-garden','Dust Garden','Particle sandbox','Jason Labbe','Damped particles receiving local radial forces and boundary bounces','Sweep dust; attract or repel; hold to gather; flick to scatter; renew the pigment.','#0a1010|#cfd299|#a8cab5','bottom',[('force','Gather / Scatter'),('seed','Fresh pigment'),('burst','Storm')],[('reach','Brush size',40,260,140,5)],
 [('var bobCount = 5000;','var bobCount = 1800;'),('b.vel.mag() * 10','max(35,b.vel.mag()*35)'),('let mouseThresh = 200;','let mouseThresh = R.amount;'),('push.mult((mouseThresh - mouseDist) * 0.01);','push.mult((mouseThresh-mouseDist)*.01*R.sign);')],init='R.amount=140;globalHue=105;reset();for(let j=0;j<100;j++){mouseX=width/2+sin(j*.1)*90;mouseY=height/2+cos(j*.1)*90;originalDraw();}',hook='if(R.pressed&&R.held>25)R.sign=-1;',up='if(abs(R.x-R.px)+abs(R.y-R.py)>4)bobs.forEach(b=>{if(dist(b.pos.x,b.pos.y,R.x,R.y)<R.amount)b.vel.add((R.x-R.px)*.12,(R.y-R.py)*.12)});',actions='if(a==="force")R.sign*=-1;if(a==="reach")R.amount=+v;if(a==="seed")reset();if(a==="burst")bobs.forEach(b=>b.vel=p5.Vector.random2D().mult(random(3,6)));')
add(742403,'06-tidal-ink','Tidal Ink','perlin sea colors','Vamoss','Persistent paths advected through a noise-angle vector field','Paint currents; stir or erase locally; ocean/sunset palettes; variable current speed.','#162a25|#cdedae|#77c39c','card',[('palette','Ocean / Sunset'),('erase','Ink / Eraser'),('clear','Clean paper')],[('speed','Current',.2,2,.6,.1)],
 [('const moveSpeed = 0.4;','let moveSpeed = .6;'),('let angle = noise(x / moveScale, y / moveScale) * TWO_PI * moveScale;','let angle=noise(x/moveScale,y/moveScale)*TWO_PI*moveScale;if(R.pressed&&dist(x,y,mouseX,mouseY)<120)angle+=atan2(y-mouseY,x-mouseX)+HALF_PI;')],
 init='for(let j=0;j<180;j++)originalDraw();',move='if(R.mode%2){fill("#162a25");circle(R.x,R.y,64);}else{for(let k=0;k<8;k++)pos.push({x:R.x+random(-30,30),y:R.y+random(-30,30),c:random(colors)});if(pos.length>1600)pos.splice(0,8);}',actions='if(a==="speed")moveSpeed=+v;if(a==="erase")R.mode++;if(a==="clear")background("#162a25");if(a==="palette"){R.palette++;colors=(R.palette%2?["#ff784f","#e8ae66","#f6e8c8","#bf3d4e"]:["#77c39c","#55aba5","#cdedae"]).map(c=>color(c));pos.forEach(p=>p.c=random(colors));}')
add(762695,'07-living-coral','Living Coral','T-Virus','Jason Labbe','Recursive branch construction with spring-driven angular dynamics','Brush branches to bend; tune spring strength; regrow the coral and change its mineral colour.','#f0e5d7|#a34c3d|#7d9182','corner',[('seed','Regrow'),('palette','Clay / Jade')],[('spring','Spring',.1,1.5,.5,.1)],
 [('background(0);','background("#f0e5d7");'),('treeIterator(rootBranches[i], 0, -height / 2, 0);','treeIterator(rootBranches[i],0,0,0);'),('stroke(230);','stroke("#a34c3d");'),('strokeWeight(25);','strokeWeight(10);'),('stroke(map(branch.level, 0, maxLevel, 255, 50));','stroke(lerpColor(color(R.palette%2?"#164e46":"#863529"),color("#d9a685"),branch.level/(maxLevel+1)));'),('worldY + height - 20','worldY + height / 2'),('random(30.0, 100.0)','random(min(width,height)*.035,min(width,height)*.12)'),('text(\n\t"".concat(','void(\n\t"".concat(')],actions='if(a==="seed")generateNewTree();if(a==="palette")R.palette++;if(a==="spring")branchForce=+v;')
add(828863,'08-prism-seal','Prism Seal','Kaleidoscope','Richard Bourne','Rotated copies of pointer-distance-sized circles','Draw mirrored glass; choose six/twelve/twenty-four slices; hold to grow a seal; clear or invert paper.','#f4eee4|#71539c|#b47697','round',[('slices','6 / 12 / 24'),('paper','Paper / Night'),('clear','Clear')],[('size','Bead size',4,32,14,1)],
 [('colourMode(HSB);','colorMode(HSB,360,100,100,1);angleMode(DEGREES);background("#f4eee4");'),('var pieces = 12;','var pieces = [6,12,24][R.mode%3];'),('repeat(0, 359, 360 / pieces, my_shapes);','if(R.pressed||!R.touched)for(let a=0;a<360;a+=360/pieces)my_shapes(a);'),('15 * 100/d','min(R.amount*100/max(d,12),60)')],init='R.amount=14;for(let k=0;k<130;k++){mouseX=width/2+cos(k*3)*width*.22;mouseY=height*.48+sin(k*3)*width*.22;push();originalDraw();pop();}',hook='if(R.pressed&&R.held>20){R.x+=sin(frameCount*.08)*.8;R.y+=cos(frameCount*.08)*.8;mouseX=R.x;mouseY=R.y;}',actions='if(a==="slices")R.mode++;if(a==="size")R.amount=+v;if(a==="paper"){R.palette++;background(R.palette%2?"#100f21":"#f4eee4");}if(a==="clear")background(R.palette%2?"#100f21":"#f4eee4");')
add(944742,'09-aurora-smoke','Aurora Smoke','Colorful smoke','Jason Labbe','Age-based ribbon strokes with a changing colour glow and rising tail','Draw luminous smoke; hold for a fountain; choose a colour band and adjust plume lifetime.','#030b16|#89e7ef|#aac7fc','caption',[('band','Ice / Flame / Violet'),('clear','Exhale')],[('life','Trail',25,100,55,5)],
 [('var maxAge = 40;','var maxAge = 55;'),('160, 10','90, 8'),('60 * particles[i].sizeVariance','30 * particles[i].sizeVariance'),('stroke(0, map(particles[i].age, 0, maxAge, 0, 255));','stroke(particles[i].hue,110,170,map(particles[i].age,0,maxAge,0,140));'),('globalHue = random(255);','globalHue=R.ink;'),('text("Move the mouse around", width / 2, 40);','// Instructions moved into HTML.')],hook='R.ink=[135,12,195][R.palette%3]+sin(frameCount*.012)*12;if(R.pressed&&R.held>8){particles.push(new Particle(R.x+sin(frameCount*.2)*18,R.y+cos(frameCount*.17)*8));globalHue=R.ink;}if(particles.length>100)particles.splice(0,particles.length-100);',actions='if(a==="band")R.palette++;if(a==="life")maxAge=+v;if(a==="clear")particles=[];')
add(897944,'10-thread-comets','Thread Comets','Lines Brush','Jason Labbe','Velocity-driven Sparks and ParticleLine trails','Flick to stretch threads; hold to build a spark fountain; select warm/cool pigments and density.','#05050b|#f3a48b|#c7a6ff','side',[('palette','New pigment'),('burst','Fireworks')],[('density','Threads',1,8,3,1)],
 [('let mass = this.mass * this.vel.mag() * 0.6;','let mass=min(28,this.mass*this.vel.mag()*.24);'),('drawingContext.shadowBlur = mass;','drawingContext.shadowBlur = min(mass,9);'),('stroke(0);','stroke(red(c),green(c),blue(c),100);'),('particles.push(new Spark(pos.x, pos.y, vel.x, vel.y));','if(R.pressed||!R.touched)particles.push(new Spark(pos.x,pos.y,vel.x,vel.y));'),('particles.push(new ParticleLine(pos.x, pos.y, vel.x, vel.y));','if(R.pressed||!R.touched)particles.push(new ParticleLine(pos.x,pos.y,vel.x,vel.y));')],hook='if(R.pressed&&R.held>20){R.px=R.x+cos(frameCount*.3)*8;R.py=R.y+sin(frameCount*.3)*8;pmouseX=R.px;pmouseY=R.py;}if(particles.length>420)particles.splice(0,particles.length-420);',actions='if(a==="palette")newColorScheme();if(a==="density")particleLinesPerFrame=+v;if(a==="burst")for(let k=0;k<100;k++){let d=p5.Vector.random2D().mult(12);particles.push(new Spark(width/2,height*.48,d.x,d.y));}')
add(400658,'11-alchemy-bloom','Alchemy Bloom',"Alchemist’s brush",'Jason Labbe','Local expanding or contracting spiral puffs with life-based scaling','Drag to paint; hold to bloom; switch expansion/contraction and tune brush size.','#100511|#ed9ded|#f3d0a4','stamp',[('inverse','Bloom / Gather'),('palette','New ink'),('clear','Clear')],[('scale','Bloom size',.3,1.5,.8,.1)],
 [('var globalHue = 0;','var globalHue = 200;'),('this.maxOffset = random(50, 300);','this.maxOffset = random(50,300)*R.amount;'),('text("Press any key to change the type of motion.", width/2, height-30);','// Instructions moved into HTML.')],init='R.amount=.8;',hook='if(R.pressed||!R.touched){for(let k=0;k<3;k++)particles.push(new Particle(mouseX,mouseY));globalHue=(globalHue+.15)%255;}',actions='if(a==="inverse")inverse=!inverse;if(a==="palette")globalHue=random(255);if(a==="scale")R.amount=+v;if(a==="clear"){particles=[];background(0);}')
add(987935,'12-pearl-flower','Pearl Flower','Repulsion','Jason Labbe','Phyllotaxis targets connected to spring particles with local repulsion','Scatter a pearl flower; hold to move its centre; burst then watch it reassemble; sea/rose palette.','#ecf1eb|#43666b|#a76c80','topbar',[('burst','Scatter pearls'),('palette','Sea / Rose')],[('reach','Touch radius',40,160,90,5)],
 [('background(50);','background("#ecf1eb");'),('strokeWeight(repulsionRadius * 2);','strokeWeight(0);'),('stroke(140, this.sat, this.bright);','stroke(R.palette%2?235:135,min(this.sat,110),min(this.bright,180));'),('stroke(0, 100);','stroke(135,40,120,35);')],hook='if(R.pressed&&R.held>25){particles.forEach((p,i)=>{let a=radians(i*137.5),r=spacing*sqrt(i);p.target.set(lerp(p.target.x,R.x+r*cos(a),.04),lerp(p.target.y,R.y+r*sin(a),.04));});}',actions='if(a==="burst")particles.forEach(p=>p.vel=p5.Vector.random2D().mult(18));if(a==="palette")R.palette++;if(a==="reach")repulsionRadius=+v;')
add(874621,'13-chromatic-breath','Chromatic Breath','Color Bubbles','Roni Kaufman, after Sayama','Golden-angle radial emitters with a distance-shaped bubble diameter','Move the emitter; hold for denser breathing; rainbow/rose colours, adjustable outward drift.','#fff7f0|#9b405c|#f3b4bc','pill',[('palette','Rainbow / Rose'),('centre','Recenter')],[('speed','Drift',.3,3,1,.1)],
 [('this.center = createVector(width/2, height/2);','this.center = createVector(R.x,R.y);'),('this.pos.add(this.dir);','this.pos.add(p5.Vector.mult(this.dir,R.rate));'),('this.col = color(map(this.dir.heading(), -PI, PI, 0, 100), 90, 100);','this.col=color(R.palette%2?95+random(-5,5):map(this.dir.heading(),-PI,PI,0,100),R.palette%2?45:80,95);'),('background(100);','background("#fff7f0");')],hook='if(R.pressed&&R.held>12)balls.push(new Ball(10,frameCount*PHI*TWO_PI+PI));if(balls.length>1200)balls.splice(0,balls.length-1200);',actions='if(a==="palette")R.palette++;if(a==="speed")R.rate=+v;if(a==="centre"){R.x=width/2;R.y=height*.48;R.touched=true;}')
add(533576,'14-silk-suspension','Silk Suspension','Dynamic ropes 2','Jason Labbe','Verlet point integration, constrained rope segments and interpolated strands','Comb the silk; grab and pull a strand; adjust gravity; change silk colour or rehang.','#e9e0d4|#79564a|#b77963','notebook',[('grab','Comb / Grab'),('palette','Copper / Ink'),('seed','Rehang')],[('weight','Weight',.01,.5,.15,.01)],
 [('var timesteps = 20;','var timesteps = 10;'),('let xCount = 40;','let xCount = 24;'),('let yCount = 20;','let yCount = 18;'),('width/2 - 150, width/2 + 150','width*.15,width*.85'),('100, 400','height*.23,height*.62'),('background(200);','background("#e9e0d4");'),('stroke(0);','stroke(R.palette%2?"#34474e":"#79564a");'),('strokeWeight(repulsionSizeSlider.value()*2);','strokeWeight(0);')],
 init='[thicknessSlider,resolutionSlider,repulsionSizeSlider,gravitySlider,airDragSlider,massSlider].forEach(s=>s.display=()=>{});gravitySlider.slider.value(.15);resolutionSlider.slider.value(.55);',hook='if(R.pressed&&R.mode%2){let best=null,bd=1e9;rigidBodies.forEach(rb=>rb.points.forEach(p=>{let d=dist(p.pos.x,p.pos.y,R.x,R.y);if(!p.snap&&d<bd){best=p;bd=d}}));if(!R.grabbed&&bd<65)R.grabbed=best;if(R.grabbed){R.grabbed.pos.set(R.x,R.y);R.grabbed.oldPos.set(R.x,R.y);}}',up='R.grabbed=null;',actions='if(a==="grab")R.mode++;if(a==="palette")R.palette++;if(a==="seed")resetScene();if(a==="weight")gravitySlider.slider.value(+v);')
add(420640,'15-mineral-light','Mineral Light','Crystal in a spotlight','Jason Labbe; original by noaner; Delaunay by ironwallaby','Per-frame Delaunay triangulation of oscillating vertices and a distance-coloured spotlight','Drag the light; hold to widen its halo; freeze the facets; select mineral hues.','#0a1024|#c7e1ed|#8791df','museum',[('freeze','Freeze / Flow'),('palette','Opal / Amber / Jade')],[('halo','Light spread',.3,1.7,1,.1)],
 [('var POINT_COUNT = 1000;','var POINT_COUNT = 260;'),('globalHue = map(noise(frameCount*0.01), 0, 1, 0, 360);','globalHue=[210,25,140][R.palette%3]+map(noise(frameCount*.01),0,1,-25,25);'),('var offset = frameCount*0.005;','R.ink+=.005*R.rate;var offset=R.ink;'),('var d = dist(mouseX, mouseY, p1[0], p1[1]);','var d=dist(mouseX,mouseY,p1[0],p1[1])/(R.amount*(R.pressed?1.5:1));')],actions='if(a==="freeze")R.rate=R.rate?0:1;if(a==="palette")R.palette++;if(a==="halo")R.amount=+v;')
add(567934,'16-firefly-tracks','Firefly Tracks','Steering path following','Jason Labbe','Particles seek successive path vertices and reverse at the ends','Draw your own flight path; release to follow it; change firefly hue, guide visibility and flight speed.','#0b1420|#c5dc83|#8baacf','route',[('seed','New route'),('guide','Guide on / off'),('palette','New swarm')],[('speed','Flight',.3,3,1,.1)],
 [('i < 2000','i < 900'),('this.mass = random(40);','this.mass = random(3,14);'),('let distThresh = 50;','let distThresh = 16;'),('255, 10);','255, 70);'),('steer.mult(0.05 * this.variance * proximityMult);','steer.mult(.1*this.variance*proximityMult*R.rate);'),('stroke(30);','stroke(R.mode%2?10:55);')],
 down='R.route=[createVector(R.x,R.y)];',move='if(R.route&&dist(R.x,R.y,R.route[R.route.length-1].x,R.route[R.route.length-1].y)>15)R.route.push(createVector(R.x,R.y));',up='if(R.route?.length>1){mainPath.vertices=R.route;bobs.forEach(b=>{b.vertIndex=0;b.direction=1;});}R.route=null;',actions='if(a==="seed")reset();if(a==="guide")R.mode++;if(a==="palette"){globalHue=random(255);bobs.forEach(b=>b.hue=(globalHue+random(-25,25))%255);}if(a==="speed")R.rate=+v;')
add(744884,'17-porcelain-tiles','Porcelain Tiles','Hexagon Pattern','Vamoss; inspiration Aida Inma','Hexagonal arc masks with interpolated sixty-degree tile rotations','Tap a tile; drag a chain; rotate every tile in a wave; shuffle or change ink.','#faf3e4|#254e67|#c5883f','tilebar',[('wave','Turn all'),('shuffle','Shuffle'),('palette','Blue / Rust')],[],
 [('const radius = 100;','const radius = 55;'),('hexagonLines.noFill();','hexagonLines.noFill();hexagonLines.stroke("#254e67");'),('hexagonLines.stroke(255);','hexagonLines.stroke("#faf3e4");'),('background(255);','background("#faf3e4");')],down='changed=findClosest();rotations[changed]+=TWO_PI/6;',move='let j=findClosest();if(j!==changed){changed=j;rotations[j]+=TWO_PI/6;}',actions='if(a==="wave")rotations=rotations.map(r=>r+TWO_PI/6);if(a==="shuffle")rotations=rotations.map(()=>TWO_PI/6*floor(random(6)));if(a==="palette"){R.palette++;document.querySelector("canvas").style.filter=R.palette%2?"sepia(.7) hue-rotate(320deg)":"none";}')
add(697866,'18-wave-letters','Wave Letters','Hello Curves','Vamoss','Glyphs rotate along the derivative of a noise-generated liquid surface','Write your own word; drag the word and sea level; tune wave texture and paper colour.','#f4dfb8|#a44936|#5e786a','type',[('palette','Terracotta / Forest'),('float','Float / Follow')],[('texture','Wave texture',.001,.012,.003,.001)],
 [('const textToWrite = "Hello curves";','let textToWrite="slow days";'),('const frequency = 0.003;','let frequency=.003;'),('textSize(150);','textFont("Georgia");textSize(min(64,width*.14));'),('background(255);','background("#f4dfb8");'),('fill(0);','fill(R.palette%2?"#405c50":"#a44936");'),('amplitude = -(mouseY / 3 + 50);','centerY=lerp(centerY,R.mode%2?height*.6:mouseY+80,.035);amplitude=-(100+abs(mouseX-width/2)*.6);')],
 move='startX=R.x-textWidth(textToWrite)/2;',actions='if(a==="palette")R.palette++;if(a==="float")R.mode++;if(a==="texture")frequency=+v;if(a==="word"){textToWrite=v.slice(0,14)||"breathe";startX=width/2-textWidth(textToWrite)/2;}',extra='<label class="word">YOUR WORD<input data-action="word" value="slow days" maxlength="14" aria-label="Your word"></label>')
add(1052362,'19-botanical-seal','Botanical Seal','Symmetric Circular Random Walker','Vamoss','Circular random walk copied around a rotational centre','Plant a new seal by tapping; drag its symmetry centre; choose six/ten/sixteen folds, ink and growth speed.','#f4f0df|#276154|#b4523f','print',[('folds','6 / 10 / 16'),('palette','Jade / Vermilion'),('clear','Fresh paper')],[('growth','Growth',1,6,2,1)],
 [('background(255);','background("#f4f0df");'),('rot += TWO_PI/6','rot += TWO_PI/[6,10,16][R.mode%3]'),('translate(width/2, height/2)','translate(R.cx,R.cy)'),('translate(-width/2, -height/2)','translate(-R.cx,-R.cy)'),('line(prevPos.x, prevPos.y, pos.x, pos.y)','stroke(R.palette%2?"#b4523f":"#276154");strokeWeight(.8);line(prevPos.x,prevPos.y,pos.x,pos.y)'),('angle += 1/radius*dir','angle += 1/radius*dir*R.rate')],
 init='R.cx=width/2;R.cy=height*.48;pos={x:R.cx+30,y:R.cy};prevPos={...pos};R.rate=2;for(let k=0;k<1800;k++)originalDraw();',down='R.cx=R.x;R.cy=R.y;pos={x:R.x+20,y:R.y};prevPos={...pos};',move='R.cx=R.x;R.cy=R.y;',actions='if(a==="folds")R.mode++;if(a==="palette")R.palette++;if(a==="clear")background("#f4f0df");if(a==="growth")R.rate=+v;')
# Original OBJ files are embedded as data URLs. loadModel recognises the .obj fragment.
face=SRC/'1200087'
assetmap={p.name:'data:text/plain;base64,'+__import__('base64').b64encode(p.read_bytes()).decode()+'#.obj' for p in face.glob('*.obj')}
# p5 1.3.1 checks the filename suffix and then loadStrings fetches the data URL.
facepatch=[("myFont = loadFont('Roboto-Black.ttf');","// No font is required after removing the original instruction panel."),("loadModel(name + '.obj')","loadModel(FACE_ASSETS[name+'.obj'],false,m=>m.gid='face-'+name)"),('textFont(myFont);','// English HTML UI uses system fonts.'),('background(50);','background("#f1e9df");'),('scale(100);','scale(min(100,width*.24));'),('return mouseDist < this.size * 0.5;','return mouseDist < max(16,this.size*.5);'),('stroke(255, 0, 0);','stroke(90,130,135);'),('stroke(0, 255, 0);','stroke(180,100,70);'),('stroke(255, 255, 0);','stroke(170,140,70);'),('directionalLight(200, 50, 50, 0.2, -0.48, 0.5);','directionalLight(180,180,170,.2,-.48,.5);'),('ambientMaterial(180, 125, 110);','ambientMaterial(R.palette%2?170:225,R.palette%2?125:215,R.palette%2?80:200);')]
main=(face/'main.js').read_text();start=main.index('\ttext(`');end=main.index('\n\tpush();',start);facepatch.append((main[start:end],'// Instructions moved into the HTML UI.\n'))
# Preserve original event handlers under new names before the shared pointer wrapper owns events.
blend=(face/'blendMesh.js').read_text();bs=blend.index('\t\tthis.mesh._edgesToVertices();');be=blend.index('\n\t}',bs)
facepatch.append((blend[bs:be],"\t\tif(drawEdges)this.mesh._makeTriangleEdges()._edgesToVertices();\n\t\tcanvas.createBuffers(this.mesh.gid,this.mesh);"))
facepatch += [('function mousePressed()','function activateFaceControl()'),('function mouseReleased()','function releaseFaceControl()')]
add(1200087,'20-porcelain-expressions','Porcelain Expressions','Facial Rig','Jason Labbe; Ray character by CGTarian Online School','Original 3D meshes, facial blendshapes and constrained control-to-target deformation','Drag face control points; pose smile/surprise/calm; porcelain/bronze materials and wireframe.','#f1e9df|#766253|#8fa7a1','portrait',[('smile','Smile'),('surprise','Surprise'),('calm','Calm'),('material','Porcelain / Bronze'),('edges','Wireframe')],[],facepatch,
 down='activateFaceControl();',up='releaseFaceControl();',actions='if(a==="material")R.palette++;if(a==="edges")drawEdges=!drawEdges;if(["smile","surprise","calm"].includes(a)){controls.forEach(c=>c.pos.set(c.restPos));if(a==="smile"){controls[1].pos.y-=16;controls[2].pos.y-=16;controls[9].pos.y-=8;controls[10].pos.y-=8;}if(a==="surprise"){controls[0].pos.y+=20;[3,4,7,8].forEach(i=>controls[i].pos.y-=18);}}')
f=OUT/'20-porcelain-expressions'/'sketch.js';f.write_text('const FACE_ASSETS='+json.dumps(assetmap,separators=(',',':'))+';\n'+f.read_text())
resizes={
423827:'maxDiam=min(width*.92,450);reset();',
762695:'generateNewTree();',
987935:'particles.forEach((p,i)=>{let a=radians(i*137.5),r=spacing*sqrt(i);p.target.set(width/2+r*cos(a),height/2+r*sin(a));});',
533576:'resetScene();',
420640:'points.forEach(p=>{p[0]=p[0]/ox*width;p[1]=p[1]/oy*height;});',
567934:'mainPath.vertices.forEach(p=>{p.x=p.x/ox*width;p.y=p.y/oy*height});bobs.forEach(b=>{b.pos.x=b.pos.x/ox*width;b.pos.y=b.pos.y/oy*height});',
744884:'hexagons=[];rotations=[];for(let x=-radius;x<width;x+=altitude*2){let row=0;for(let y=-radius;y<height;y+=radius*1.5){hexagons.push({x:x+(row%2?altitude:0),y,rotation:0});rotations.push(TWO_PI/6*floor(random(6)));row++;}}',
697866:'centerX=width/2;centerY=height*.55;textSize(min(64,width*.14));startX=centerX-textWidth(textToWrite)/2;',
1052362:'R.cx=width/2;R.cy=height*.48;pos={x:R.cx+30,y:R.cy};prevPos={...pos};background("#f4f0df");',
1200087:'ortho(-width/2,width/2,-height/2,height/2,0,1000);'
}
for w in works:
 p=OUT/w['slug']/'sketch.js'
 if w['id'] in resizes:p.write_text(p.read_text()+'\nR.resize=(ox,oy)=>{'+resizes[w['id']]+'};\n')
(OUT/'manifest.json').write_text(json.dumps(works,indent=2,ensure_ascii=False))
print('Built',len(works),'source-based scene scripts')
