from pathlib import Path
import json,html,zipfile,hashlib
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'remix20';works=json.loads((OUT/'manifest.json').read_text());esc=html.escape
release='https://github.com/wentaopeng714-cmd/openprocessing-loopit-20/releases/download/v6.0.0/'
rows=[];cards=[]
for w in works:
 slug=w['slug'];rows.append(f'| {slug[:2]} | [{w["title"]}]({slug}/) | [{w["original"]}](https://openprocessing.org/sketch/{w["id"]}) | {w["author"]} | CC {w["license"].upper()} | {w["algorithm"]} | {w["changes"]} |')
 badge='<span class="license">Noncommercial original</span>' if w['license']=='by-nc-sa' else ''
 cards.append(f'''<article><a class="picture" href="{slug}/" style="background:{w['theme'].split('|')[0]}"><img loading="lazy" width="390" height="844" src="{slug}/preview.png" alt="{esc(w['title'])} rendered from its adapted source"><span class="play">Explore ↗</span></a><div class="copy"><span class="number">{slug[:2]} / 20</span>{badge}<h2>{esc(w['title'])}</h2><p>{esc(w['changes'])}</p><div class="downloads"><a href="{release}{slug}.html" download>HTML ↓</a><a href="{release}{slug}.zip" download>ZIP ↓</a></div><a class="original" href="https://openprocessing.org/sketch/{w['id']}" target="_blank" rel="noopener">Original: {esc(w['original'])} ↗</a></div></article>''')
(OUT/'SOURCES.md').write_text('''# Twenty OpenProcessing source remixes

These adaptations retain actual code downloaded from the public source files of the linked OpenProcessing sketches. Each individual ZIP includes the unchanged original tabs, original assets when applicable, source file URLs and SHA256 hashes, a visual-code diff and the adapted code. Source algorithms are independent; only pointer/UI handling is shared.

Original author notices are retained. License identifiers were read from OpenProcessing metadata. Share-alike and attribution conditions continue to apply. **13 — Chromatic Breath retains CC BY-NC-SA and is limited to noncommercial use unless separately permitted.** The Facial Rig includes the Ray character credited to CGTarian Online School by Jason Labbe.

| No. | Adaptation | OpenProcessing source | Original credits | Original licence | Retained algorithm | Changes |
|---|---|---|---|---|---|---|
'''+ '\n'.join(rows)+'''

## Validation

Nineteen 2D works execute the actual vendored p5.js in a simulated DOM with native Canvas rendering. Checks cover Pointer Events, scene buttons, slider inputs, pause, UI hiding and viewport changes. The facial rig uses the original p5 1.3.1 OBJ loader and original deformation functions; 58 meshes load, smile changes 1,173 vertices, calm restores the mesh, and jaw dragging changes its control. Its thumbnail is a software projection of those meshes, not a WebGL screenshot. No live browser/GPU or real phone check was possible while the host Mac was locked.

See qa-runtime.json and qa-face.json. Runtime checks do not establish actual device performance. Gallery thumbnails are source renders, not browser screenshots.

## Rebuild

Run `python3 remix20/build.py`, `python3 remix20/package.py`, the Node runtime checks, then `python3 remix20/gallery.py` from the repository root. Source snapshots live in `research/op-new-20/`. The source text is preserved as downloaded; all subsequent edits are in the remix folders. p5.js LGPL notices accompany each ZIP.
''')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Twenty OpenProcessing Remixes</title><meta name="description" content="20 source-based OpenProcessing adaptations, made for touch. Play and download each independent HTML or ZIP."><style>*{box-sizing:border-box}body{margin:0;background:#f0eee7;color:#242b28;font-family:Arial,sans-serif}main{max-width:1400px;margin:auto;padding:35px 30px}header{border-top:1px solid #92988b;padding:25px 0 50px;display:grid;grid-template-columns:1.3fr 1fr;gap:35px}small,.number{font-size:10px;letter-spacing:.15em;text-transform:uppercase}h1{font:clamp(40px,6vw,78px)/.98 Georgia,serif;letter-spacing:-.045em;font-weight:400;margin:25px 0}header p{max-width:400px;font-size:15px;line-height:1.7;margin:35px 0 20px}header nav{display:flex;flex-wrap:wrap;gap:10px}a{color:inherit}header nav a{padding:13px 18px;border:1px solid #5c665d;text-decoration:none;border-radius:30px;font-size:12px}header nav a:first-child{background:#394b40;color:#f7f2e7}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:35px 22px}article{border-top:1px solid #b4b9ac}.picture{position:relative;display:block;height:350px;overflow:hidden;margin-top:12px}.picture img{display:block;width:100%;height:100%;object-fit:cover;object-position:center 46%;transition:transform .4s}.picture:hover img{transform:scale(1.035)}.play{position:absolute;bottom:12px;right:12px;background:#f4f0e9dd;color:#28342e;padding:10px 14px;border-radius:30px;font-size:11px}.copy{padding-top:16px}h2{font:27px Georgia,serif;margin:9px 0}article p{font-size:12px;line-height:1.65;color:#69716a;min-height:78px}.downloads{display:flex;gap:8px;margin:15px 0}.downloads a{font-size:11px;text-decoration:none;border:1px solid #a0a99c;padding:10px 17px;border-radius:25px}.original{font-size:10px;color:#65715f;line-height:1.6;text-underline-offset:3px}.license{display:block;font-size:9px;color:#975446;margin-top:8px}.note{font-size:11px!important;color:#6a7267}footer{margin-top:50px;padding:20px 0;border-top:1px solid #a0a99c;font-size:11px;line-height:1.8;color:#69716a}@media(max-width:1100px){.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}header{grid-template-columns:1fr;gap:0}header p{margin-top:0}}@media(max-width:480px){main{padding:25px 18px}.grid{grid-template-columns:1fr;gap:35px}.picture{height:430px}article p{min-height:0}h1{font-size:54px}header{padding-bottom:35px}}</style></head><body><main><header><div><small>OPENPROCESSING / SOURCE REMIX COLLECTION</small><h1>Twenty ways<br>to touch.</h1></div><div><p>Twenty existing OpenProcessing artworks, adapted from their real source code. Shape, draw, bend, stir and pose. Each work has its own controls and an independent offline upload file.</p><nav>'''
page+=f'<a href="{release}openprocessing-remix20-all.zip" download>Download all 20 ZIPs ↓</a><a href="sources.html">Originals & credits ↗</a></nav><p class="note">English UI · Touch & mouse · Individual HTML + ZIP<br>13 / Chromatic Breath: noncommercial source licence.</p></div></header><section class="grid" aria-label="Twenty artworks">'+''.join(cards)+'</section><footer>Original artists retain their credit and licence. Each package includes source provenance.<br>Thumbnails are rendered from the adapted code. The facial thumbnail uses a software projection; browser WebGL verification is pending.<br><a href="../upload-art/">First six</a> · <a href="../upload-art-2/">Second six</a> · <a href="SOURCES.md">Detailed provenance and validation</a></footer></main></body></html>'
(OUT/'index.html').write_text(page)
sourcecards=''.join(f'<tr><td>{w["slug"][:2]}</td><td><a href="{w["slug"]}/">{esc(w["title"])}</a></td><td><a href="https://openprocessing.org/sketch/{w["id"]}">{esc(w["original"])}</a><br>{esc(w["author"])}</td><td>{esc(w["algorithm"])}</td><td>CC {w["license"].upper()}</td></tr>' for w in works)
(OUT/'sources.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Originals & Credits</title><style>body{background:#f0eee7;color:#28342e;font:14px/1.6 Arial;margin:30px}h1{font:42px Georgia}table{border-collapse:collapse;width:100%}td,th{padding:15px;text-align:left;border-bottom:1px solid #aaa;vertical-align:top}a{color:inherit}.table{overflow:auto}</style><a href="./">← Collection</a><h1>Originals & credits.</h1><p>Each adaptation preserves the linked work’s source algorithm. Unchanged originals, file hashes and changes are included in its ZIP.</p><p>Chromatic Breath uses a CC BY-NC-SA source. Ray character meshes in Facial Rig are credited to CGTarian Online School by the original author.</p><div class="table"><table><tr><th>No.</th><th>Adaptation</th><th>OpenProcessing original & author</th><th>Retained algorithm</th><th>Source licence</th></tr>'+sourcecards+'</table></div><p><a href="SOURCES.md">Detailed provenance & validation</a></p></html>')
with zipfile.ZipFile(OUT/'openprocessing-remix20-all.zip','w',zipfile.ZIP_STORED) as z:
 for w in works:z.write(OUT/(w['slug']+'.zip'),w['slug']+'.zip')
 z.write(OUT/'SOURCES.md','SOURCES.md')
files=[OUT/(w['slug']+ext) for w in works for ext in ['.html','.zip']]+[OUT/'openprocessing-remix20-all.zip']
(OUT/'SHA256SUMS.txt').write_text(''.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+p.name+'\n' for p in files))
im=Image.new('RGB',(5*234,4*550),'#e5e1d8');d=ImageDraw.Draw(im)
for i,w in enumerate(works):
 p=Image.open(OUT/w['slug']/'preview.png').convert('RGB');p.thumbnail((218,480));x=i%5*234+8;y=i//5*550+8;im.paste(p,(x,y));d.text((x,y+488),w['slug'][:2]+' / '+w['title'],fill='#303730');d.text((x,y+508),'OP '+str(w['id']),fill='#60665b')
im.save(OUT/'overview.jpg',quality=90)
print('Gallery, provenance, overview, checksums and combined ZIP ready')
